theme: jekyll-theme-minimal
title: Junkil Park
description: Research Engineer at Aptos Labs
logo: https://media-exp1.licdn.com/dms/image/C5603AQHwhWf6zmmARA/profile-displayphoto-shrink_800_800/0/1575957674113?e=1666224000&v=beta&t=ybwH1gYUf1PCXJaWoHykeuL0x_RNFisMeFl-QcGg5EI
show_downloads: false
